ap:
  igwBaseURL: "http://infra-sim-inference-gateway-istio.llm-d-sim.svc.cluster.local:80"
  image:
    repository: ghcr.io/llm-d/async-processor
    tag: v0.0.1
  imagePullPolicy: Never

  metrics:
    enabled: true
    port: 9090
    secure: false

  gcpPubSub:
    enabled: false
    requestSubscriberId: xxx
    resultTopicId: xxx 
    requestPathURL: "/v1/completions"


  redis:
     enabled: true
     port: 6379
     host: "redis-master.redis.svc.cluster.local"
     requestPathURL: "/v1/completions"
  


